name: Deploy to Bunny.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Bunny Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: '.'  
          storageZoneName: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
          storagePassword: ${{ secrets.BUNNY_ACCESS_KEY }}
          storageEndpoint: 'la.storage.bunnycdn.com'
          accessKey: ${{ secrets.BUNNY_API_KEY }} 
          pullZoneId: ${{ secrets.BUNNY_PULL_ZONE_ID }} 
          upload: true
          removeConfig: false
          purgePullZone: true 
