name: Deploy to Bunny.net

on:
  push:
    branches:
      - main  # Change this to 'master' if your repo's default branch is called master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Bunny Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.6
        with:
          source: '.'  
          storageZoneName: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
          storagePassword: ${{ secrets.BUNNY_ACCESS_KEY }}
          storageEndpoint: 'la.storage.bunnycdn.com'
          upload: true
          removeConfig: false
          purgePullZone: true 
