name: Deploy to Bunny.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Bunny Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.6
        with:
          source: '.'  
          storageZoneName: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
          storagePassword: ${{ secrets.BUNNY_ACCESS_KEY }}
          storageEndpoint: '://bunnycdn.com'
          accessKey: ${{ secrets.BUNNY_API_KEY }} # Added for purging
          pullZoneId: ${{ secrets.BUNNY_PULL_ZONE_ID }} # Added for purging
          upload: true
          removeConfig: false
          purgePullZone: true 
